# Generated by Django 4.0 on 2022-01-03 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('earn', models.PositiveIntegerField(default=0)),
                ('bank', models.IntegerField(default=0)),
                ('deposit', models.PositiveIntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('daily_diff', models.IntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('comment', models.CharField(default='nothing', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
